In [5]:
import os
import time
import json
import cv2
from skimage.io import imsave
import numpy as np
from PIL import Image
import torch
from torchvision.transforms import functional as F


In [6]:
image = '/home/hywel/Documents/maskrcnn-benchmark/datasets/coco/restricted/190109_180343_00154162.jpg'

In [16]:
a = torch.randn(5, 4)
b = torch.randn(3, 4) 
c = [a,b] 

In [17]:
torch.cat(c,0)

tensor([[ 0.4823, -0.6029, -1.1229,  2.0618],
        [-0.7822,  0.3828,  2.7564,  0.0151],
        [-0.9441,  1.1970,  0.5694, -0.1577],
        [-1.3669,  0.9447, -1.3999,  0.1145],
        [ 0.1918,  0.9042, -0.2347,  2.1393],
        [ 0.9140,  0.0925, -0.4290,  0.7432],
        [ 0.6056, -0.5662, -2.0235, -1.6594],
        [-0.7654,  0.6342, -0.9653, -0.7838]])

In [29]:
tmp = [0, 2]
indices = torch.tensor(tmp)

torch.index_select(a,0,indices)


tensor([[ 0.4823, -0.6029, -1.1229,  2.0618],
        [-0.9441,  1.1970,  0.5694, -0.1577]])

In [19]:
a

tensor([[ 0.4823, -0.6029, -1.1229,  2.0618],
        [-0.7822,  0.3828,  2.7564,  0.0151],
        [-0.9441,  1.1970,  0.5694, -0.1577],
        [-1.3669,  0.9447, -1.3999,  0.1145],
        [ 0.1918,  0.9042, -0.2347,  2.1393]])